spring.application.name=appauthentrace
spring.datasource.url=jdbc:postgresql://localhost:5432/db_authentrace
spring.datasource.username=postgres
spring.datasource.password=admi
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Asegura que los inserts de data.sql se ejecuten
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

spring.jpa.properties.hibernate.format_sql=true
#No envia el trace al usuario cuando hay error.
server.error.include-stacktrace=never