INSERT INTO role (id_rol, nombre_rol) VALUES (1, 'USUARIO') ON CONFLICT DO NOTHING;
INSERT INTO role (id_rol, nombre_rol) VALUES (2, 'ADMIN') ON CONFLICT DO NOTHING;
INSERT INTO roles (name) VALUES ( 'ROLE_USUARIO') ON CONFLICT DO NOTHING;
INSERT INTO roles (name) VALUES ( 'ROLE_ADMIN') ON CONFLICT DO NOTHING;
INSERT INTO users(username, password) VALUES ('user1','$2a$12$1k34YdrmxBkVborQvZLh2OUvX1S80GVVQjZJ5H55y1eez7XV.nV06') ON CONFLICT DO NOTHING;
INSERT INTO users(username, password) VALUES ('admin','$2a$12$1k34YdrmxBkVborQvZLh2OUvX1S80GVVQjZJ5H55y1eez7XV.nV06') ON CONFLICT DO NOTHING;
INSERT INTO user_roles (user_id, role_id) VALUES (1, 1) ON CONFLICT DO NOTHING; -- user1 with ROLE_USER
INSERT INTO user_roles (user_id, role_id) VALUES (2, 2) ON CONFLICT DO NOTHING; -- admin with ROLE_ADMIN